### ISSUE TITLE
Unhandled exception. System.MissingMethodException: Method not found: 'Void Nacos.BeatInfo.set_weight(Double)'

### ISSUE THREAD

**Issue by weiyan2012** [softlgl/Ocelot.Provider.Nacos#11]
1.0.0 版本 报这个错误要如何解决？
对应Nacos是2.0.3
![微信截图_20210918084943](https://user-images.githubusercontent.com/1393860/133866396-bb1b97f2-ff34-4aad-919f-8a12716df10a.png)

**Comment by softlgl** [comment]
1.1.0 版本才支持nacos2.x
