### ISSUE TITLE
nacos开启身份认证后，通过Ocelot.Provider.Nacos无法注册到Nacos注册中心

### ISSUE THREAD

**Issue by feiyue2008** [softlgl/Ocelot.Provider.Nacos#4]
设置为true就Ocelot网关服务就注册不进去

**Comment by softlgl** [comment]
> 设置为true就Ocelot网关服务就注册不进去

您好，nacos访问组件使用的[nacos-sdk-csharp](https://github.com/catcherwong/nacos-sdk-csharp)您可以去看一看这个组件是否支持身份认证，Ocelot.Provider.Nacos保留了[nacos-sdk-csharp](https://github.com/catcherwong/nacos-sdk-csharp)的原始使用方式。
