### ISSUE TITLE
能适配新的nacos-sdk-csharp吗

### ISSUE THREAD

**Issue by pccai** [softlgl/Ocelot.Provider.Nacos#6]
官方1.0.0版本的nacos-sdk-csharp-unofficial 已经去掉-unofficia后缀了。

**Comment by softlgl** [comment]
近期打算升级到nacos2.0-beta试试

**Comment by softlgl** [comment]
@pccai 近期打算升级到nacos2.0-beta试试

**Comment by YYCMZERO** [comment]
@softlgl 有升级到nacos2.0吗？

**Comment by softlgl** [comment]
> @softlgl 有升级到nacos2.0吗？

我在本地已经尝试升级了，但是使用nacos-sdk-csharp v1.1.0注册不到nacos2.0上，目前还不知道啥问题，我试了试官方的demo好像也不行，有空我咨询一下作者

**Comment by softlgl** [comment]
> @softlgl 有升级到nacos2.0吗？

我在本地已经尝试升级了，但是使用nacos-sdk-csharp v1.1.0注册不到nacos2.0上，目前还不知道啥问题，我试了试官方的demo好像也不行，有空我咨询一下作者
